# Generated by Django 4.2.18 on 2025-02-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
