# Generated by Django 4.2.18 on 2025-02-01 11:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='CompanyProfile',
        ),
        migrations.RenameModel(
            old_name='Hunter',
            new_name='HunterProfile',
        ),
    ]
