# Generated by Django 4.2.18 on 2025-02-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_project_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
