# Generated by Django 4.2.18 on 2025-02-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_companyprofile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='post_type',
            field=models.CharField(choices=[('DISCUSSION', 'Discussion'), ('BUG', 'Bug')], default='DISCUSSION', max_length=60),
        ),
    ]
