# Generated by Django 4.2.18 on 2025-02-01 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_hunterprofile_bugs_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunterprofile',
            name='rewards_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
