# Generated by Django 4.2.18 on 2025-02-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_hunterprofile_rewards_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='pfp/company/'),
        ),
        migrations.AddField(
            model_name='hunterprofile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='pfp/hunter/'),
        ),
    ]
