# Generated by Django 4.2.18 on 2025-02-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_companyprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
