# Generated by Django 4.2.18 on 2025-02-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_projectpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='projects_joined', to='base.hunterprofile'),
        ),
    ]
