# Generated by Django 4.2.18 on 2025-02-13 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_project_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='high_bounty',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10, validators=[django.core.validators.MinValueValidator(500.0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='low_bounty',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10, validators=[django.core.validators.MinValueValidator(20.0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='medium_bounty',
            field=models.DecimalField(decimal_places=2, default=125.0, max_digits=10, validators=[django.core.validators.MinValueValidator(125.0)]),
        ),
    ]
