# Generated by Django 4.2.18 on 2025-02-13 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_project_high_bounty_project_low_bounty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunterprofile',
            name='rating',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=10, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
