# Generated by Django 4.2.18 on 2025-02-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_hunterprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunterprofile',
            name='rating_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
