# Generated by Django 4.2.18 on 2025-02-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_hunterprofile_rating_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunterprofile',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
